### ISSUE TITLE
Remove (and ignore later on) IDE artefacts and unnecessary/temporary files

### ISSUE THREAD

**Issue by pkorotkov** [pkorotkov/nd_210_2016#2]
Удалить из репозитория и игнорировать впредь (используя файл gitignore) артефакты сред разработки (например, папку ".idea"), а также всё, что не является необходимыми для сборки приложения (например, папки "\_\_pycache\_\_" и файлы с расширением "pic").

**Comment by helgenowl** [comment]
JetBrains говорит расшаривать папку .idea за исключением лишь некоторых файлов
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

**Comment by pkorotkov** [comment]
Это очень не хорошая практика, которая имеет оправдание разве что в enterprise-проектах, где у *всех* разработчиков одна IDE, да ещё и (желательно) одной версии. Кстати, там же, в комментариях, на этот счёт люди говорят [правильные вещи](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839/comments/200744669). В ситуации, где нет жесткой привязки к среде разработки, а это имеет место везде в мире open source, оставлять локальный мусор IDE считается дурным тоном.
